package com.mycompany.myapp;

import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;

import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;

import com.codename1.ui.Toolbar;
import com.mycompany.Gui.SplashScreen;
import com.mycompany.Gui.signin;
import com.mycompany.Service.ProductService;

import java.io.IOException;


/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;

    private Resources theme;

    ProductService serv = new ProductService();

    public void init(Object context) {

        //theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);
        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        //AllProduct all=new AllProduct(serv.getList());
        //all.getF().show();
        SplashScreen spsc = new SplashScreen();
        signin sign = new signin();
        
        try {
            spsc.startApp();
        } catch (IOException ex) {
        }

        new java.util.Timer().schedule(
                new java.util.TimerTask() {
            @Override
            public void run() {
                sign.getLogin().show();
            }
        },
                4000
        );

    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }

    public void destroy() {
    }

}
